#!/usr/bin/env Rscript
#
# This script generates .Rd files for a list of chosen auto-generated S4 classes
# can be invoked from a shell script, e.g.:
# path/to/package/source/inst/docGen/autoGeneratedRdFiles.R path/to/package/source
# 
# Author: brucehoff
###############################################################################

# This generates one .Rd file for an auto-generated S4 class using its JSON schema
createRdFromSchema<-function(className, schemaName) {
  nameLine<-paste("\\name{", className, "}", sep="")
  aliasLine<-paste("\\alias{", className, "}", sep="")
  docTypeLine<-paste("\\docType{methods}", sep="")
  titleLine<-paste("\\title{\n", className, " Constructor\n}", sep="")
  descriptionLine<-paste("\\description{Constructor for ", className, "}", sep="")
  slots<-getSlots(className)
  usageLine<-paste("\\usage{", className, "(", paste(names(slots), collapse=", "), ")}", sep="")
  
  propertySchemas<-getEffectivePropertySchemas(schemaName)
  arguments<-"\\arguments{"
  for (propertyName in names(propertySchemas)) {
    arguments<-paste(arguments, 
      itemRdEntry(propertyName, propertySchemas[[propertyName]]$description), sep="\n")
  }
  arguments<-paste(arguments, "}", sep="\n")
  slots<-"\\section{Slots}{\n  \\describe{"
  for (propertyName in names(propertySchemas)) {
    slots<-paste(slots, slotRdEntry(propertyName, propertySchemas[[propertyName]]$description), sep="\n")
  }
  slots<-paste(slots, "  }\n}", sep="\n")
  seealso<-"\\seealso{"
  for (property in propertySchemas) {
    if (!is.null(property[["$ref"]])) {
      tryCatch(expr={
          # will throw exception if the schema hasn't been defined as a class in the package.  If so just skip it
          referencedClass<- getS4ClassNameFromSchemaName(property[["$ref"]])
          seealso<-paste(seealso, paste("\\code{\\link{",referencedClass, "}}", sep=""), sep="\n")
        }, error=function(e){})
    }
  }
  seealso<-paste(seealso, "}", sep="\n")
  result<-paste(
    nameLine, 
    aliasLine, 
    docTypeLine, 
    titleLine, 
    usageLine,
    arguments,
    slots,
    seealso,
    sep="\n")
  
  result
}

itemRdEntry<-function(itemName, itemDescription) {
  paste("  \\item{", itemName, "}{\n  ", itemDescription, "\n  }", sep="")
}

slotRdEntry<-function(itemName, itemDescription) {
  paste("    \\item{\\code{", itemName, "}}{\n    ", itemDescription, "\n    }", sep="")
}

# create the autogenerated files
# clientDir is the root directory for the code base
# the schemas are found in <clienDir>/inst/resources/schema
# the target dir is <clientDir>/man
autoGenerateRdFiles<-function(clientDir) {
  if (!file.exists(clientDir)) {
    stop(sprintf("%s does not exist.", clientDir))
  }
  filePath<-sprintf("%s/inst/resources/s4ClassesToGenerate.txt", clientDir)
  s4ClassesToAutoGenerate<-read.table(filePath,
    header=TRUE, colClasses=c("character", "character", "logical"))
  
  for(i in 1:(dim(s4ClassesToAutoGenerate)[1])) { 
    schemaName<-s4ClassesToAutoGenerate[i,"schemaName"]
    className<-s4ClassesToAutoGenerate[i,"className"]
    if (s4ClassesToAutoGenerate[i,"docGen"]) {
      rdContent<-createRdFromSchema(className, schemaName)
      connection<-file(sprintf("%s/man/%s.Rd", clientDir, className))
      writeChar(rdContent, connection, eos=NULL)
      close(connection)
    }
  }
}

# now call autoGenerateRdFiles
args <- commandArgs(TRUE)
autoGenerateRdFiles(args[1])
