#!/usr/bin/env Rscript
#
# This script generates .Rd files for a list of chosen auto-generated S4 classes
# can be invoked from a shell script, e.g.:
# path/to/package/source/inst/docGen/autoGeneratedRdFiles.R path/to/package/source
# 
# Author: brucehoff
###############################################################################

library(RJSONIO)

readSchema<-function(schemaName) {
  file <- sprintf("%s.json", gsub("[\\.]", "/", name))
  
}
# This generates one .Rd file for an auto-generated S4 class using its JSON schema
createRdFromSchema<-function(className, schemaName, schemaPath, classToSchemaMap) {
  nameLine<-paste("\\name{", className, "}", sep="")
  aliasLine<-paste("\\alias{", className, "}", sep="")
  docTypeLine<-paste("\\docType{methods}", sep="")
  titleLine<-paste("\\title{\n", className, " Constructor\n}", sep="")
  descriptionLine<-paste("\\description{Constructor for ", className, "}", sep="")
  
  propertySchemas<-getEffectivePropertySchemas(schemaName, schemaPath)
  usageLine<-paste("\\usage{", className, "(", paste(names(propertySchemas), collapse=", "), ")}", sep="")
  
  arguments<-"\\arguments{"
  for (propertyName in names(propertySchemas)) {
    propertySchema <- propertySchemas[[propertyName]]
    arguments<-paste(arguments, 
      itemRdEntry(propertyName, propertySchema$description, propertySchema$type), sep="\n")
  }
  arguments<-paste(arguments, "}", sep="\n")
  slots<-"\\section{Slots}{\n  \\describe{"
  for (propertyName in names(propertySchemas)) {
    propertySchema <- propertySchemas[[propertyName]]
    slots<-paste(slots, slotRdEntry(propertyName, propertySchema$description, propertySchema$type), sep="\n")
  }
  slots<-paste(slots, "  }\n}", sep="\n")
  seealso<-"\\seealso{"
  for (property in propertySchemas) {
    referencedSchema<-NULL
    if (property$type=="array") {
      arraySubSchema<-getArraySubSchema(property)
      referencedSchema<-arraySubSchema[["$ref"]]
    } else {
      referencedSchema<- property[["$ref"]]
    }
    referencedClass<-NULL
    if (!is.null(referencedSchema)) {
      referencedClass<- classToSchemaMap[[referencedSchema]]
    }
    if (!is.null(referencedClass)) {
      seealso<-paste(seealso, paste("\\code{\\link{",referencedClass, "}}", sep=""), sep="\n")
    }
  }
  seealso<-paste(seealso, "}", sep="\n")
  result<-paste(
    nameLine, 
    aliasLine, 
    docTypeLine, 
    titleLine, 
    usageLine,
    arguments,
    slots,
    seealso,
    sep="\n")
  
  result
}

itemRdEntry<-function(itemName, itemDescription, itemType) {
  paste("  \\item{", itemName, "}{\n  ", itemDescription, " (", itemType, ")\n  }", sep="")
}

slotRdEntry<-function(itemName, itemDescription, itemType) {
  paste("    \\item{\\code{", itemName, "}}{\n    ", itemDescription, " (", itemType, ")\n    }", sep="")
}

# create the autogenerated files
# srcRootDir is the root directory for the code base
# the schemas are found in <srcRootDir>/inst/resources/schema
# the target dir is <srcRootDir>/man
autoGenerateRdFiles<-function(srcRootDir) {
  if (!file.exists(srcRootDir)) {
    stop(sprintf("%s does not exist.", srcRootDir))
  }
  filePath<-sprintf("%s/inst/resources/s4ClassesToGenerate.txt", srcRootDir)
  s4ClassesToAutoGenerate<-read.table(filePath,
    header=TRUE, colClasses=c("character", "character", "logical"))
  schemaPath<-sprintf("%s/inst/resources/schema", srcRootDir)
  classToSchemaMap<-list()
  for(i in 1:(dim(s4ClassesToAutoGenerate)[1])) { 
    schemaName<-s4ClassesToAutoGenerate[i,"schemaName"]
    className<-s4ClassesToAutoGenerate[i,"className"]
    classToSchemaMap[[schemaName]]<-className
  }
  for(i in 1:(dim(s4ClassesToAutoGenerate)[1])) { 
    schemaName<-s4ClassesToAutoGenerate[i,"schemaName"]
    className<-s4ClassesToAutoGenerate[i,"className"]
    if (s4ClassesToAutoGenerate[i,"genDoc"]) {
      rdContent<-createRdFromSchema(className, schemaName, schemaPath, classToSchemaMap)
      fileName<-sprintf("%s/man/%s.Rd", srcRootDir, className)
      connection<-file(fileName)
      writeChar(rdContent, connection, eos=NULL)
      close(connection)
      cat(sprintf("Created %s\n", fileName))
    }
  }
}

# now call autoGenerateRdFiles
args <- commandArgs(TRUE)
srcRootDir<-args[1]
# 'source' some functions shared with the synapse client package
source(sprintf("%s/R/AAAAshared.R",srcRootDir))
autoGenerateRdFiles(srcRootDir)
